// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function MinimizeToTray():Promise<void>;

export function RestoreFromTray():Promise<void>;
