// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function MinimizeToTray() {
  return window['go']['handler']['TaskbarHandler']['MinimizeToTray']();
}

export function RestoreFromTray() {
  return window['go']['handler']['TaskbarHandler']['RestoreFromTray']();
}
