// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entity} from '../models';

export function CreateVocabularyBank(arg1:string,arg2:string):Promise<entity.VocabularyBank>;

export function DeleteVocabularyBank(arg1:number):Promise<void>;

export function GetAllVocabularyBanks():Promise<Array<entity.VocabularyBank>>;

export function GetRandomVocabulary():Promise<entity.Vocabulary>;

export function GetSelectedVocabularyBankID():Promise<number>;

export function GetVocabularyCountByVocabularyBankID(arg1:number):Promise<number>;

export function SetSelectedVocabularyBankID(arg1:number):Promise<void>;
