// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entity} from '../models';

export function AddVocabulary(arg1:entity.Vocabulary):Promise<void>;

export function DeleteVocabulary(arg1:number):Promise<void>;

export function GetStarStatus(arg1:string):Promise<entity.Vocabulary>;

export function GetWordByID(arg1:number):Promise<entity.Vocabulary>;

export function GetWordCount():Promise<number>;

export function GetWordsByRange(arg1:number,arg2:number):Promise<Array<entity.Vocabulary>>;

export function GetWordsByVocabularyBankID(arg1:number):Promise<Array<entity.Vocabulary>>;

export function UpdateVocabulary(arg1:entity.Vocabulary):Promise<void>;
