// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddVocabulary(arg1) {
  return window['go']['handler']['VocabularyHandler']['AddVocabulary'](arg1);
}

export function DeleteVocabulary(arg1) {
  return window['go']['handler']['VocabularyHandler']['DeleteVocabulary'](arg1);
}

export function GetStarStatus(arg1) {
  return window['go']['handler']['VocabularyHandler']['GetStarStatus'](arg1);
}

export function GetWordByID(arg1) {
  return window['go']['handler']['VocabularyHandler']['GetWordByID'](arg1);
}

export function GetWordCount() {
  return window['go']['handler']['VocabularyHandler']['GetWordCount']();
}

export function GetWordsByRange(arg1, arg2) {
  return window['go']['handler']['VocabularyHandler']['GetWordsByRange'](arg1, arg2);
}

export function GetWordsByVocabularyBankID(arg1) {
  return window['go']['handler']['VocabularyHandler']['GetWordsByVocabularyBankID'](arg1);
}

export function UpdateVocabulary(arg1) {
  return window['go']['handler']['VocabularyHandler']['UpdateVocabulary'](arg1);
}
