// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateVocabularyBank(arg1, arg2) {
  return window['go']['handler']['VocabularyBankHandler']['CreateVocabularyBank'](arg1, arg2);
}

export function DeleteVocabularyBank(arg1) {
  return window['go']['handler']['VocabularyBankHandler']['DeleteVocabularyBank'](arg1);
}

export function GetAllVocabularyBanks() {
  return window['go']['handler']['VocabularyBankHandler']['GetAllVocabularyBanks']();
}

export function GetRandomVocabulary() {
  return window['go']['handler']['VocabularyBankHandler']['GetRandomVocabulary']();
}

export function GetSelectedVocabularyBankID() {
  return window['go']['handler']['VocabularyBankHandler']['GetSelectedVocabularyBankID']();
}

export function GetVocabularyCountByVocabularyBankID(arg1) {
  return window['go']['handler']['VocabularyBankHandler']['GetVocabularyCountByVocabularyBankID'](arg1);
}

export function SetSelectedVocabularyBankID(arg1) {
  return window['go']['handler']['VocabularyBankHandler']['SetSelectedVocabularyBankID'](arg1);
}
