// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handler} from '../models';

export function GetMinSize():Promise<handler.MinSize>;

export function GetPinStatus():Promise<boolean>;

export function GetWindowMode():Promise<string>;

export function GetWindowOpacity():Promise<number>;

export function IsFloatWindowRunning(arg1:string):Promise<boolean>;

export function PinFloatWindow():Promise<void>;

export function SaveFloatWindowPositionAndSize():Promise<void>;

export function SetPinStatus(arg1:boolean):Promise<void>;

export function SetWindowOpacity(arg1:number):Promise<void>;

export function ToggleFloatWindow(arg1:string):Promise<boolean>;

export function UnpinFloatWindow():Promise<void>;
