// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMinSize() {
  return window['go']['handler']['WindowHandler']['GetMinSize']();
}

export function GetPinStatus() {
  return window['go']['handler']['WindowHandler']['GetPinStatus']();
}

export function GetWindowMode() {
  return window['go']['handler']['WindowHandler']['GetWindowMode']();
}

export function GetWindowOpacity() {
  return window['go']['handler']['WindowHandler']['GetWindowOpacity']();
}

export function IsFloatWindowRunning(arg1) {
  return window['go']['handler']['WindowHandler']['IsFloatWindowRunning'](arg1);
}

export function PinFloatWindow() {
  return window['go']['handler']['WindowHandler']['PinFloatWindow']();
}

export function SaveFloatWindowPositionAndSize() {
  return window['go']['handler']['WindowHandler']['SaveFloatWindowPositionAndSize']();
}

export function SetPinStatus(arg1) {
  return window['go']['handler']['WindowHandler']['SetPinStatus'](arg1);
}

export function SetWindowOpacity(arg1) {
  return window['go']['handler']['WindowHandler']['SetWindowOpacity'](arg1);
}

export function ToggleFloatWindow(arg1) {
  return window['go']['handler']['WindowHandler']['ToggleFloatWindow'](arg1);
}

export function UnpinFloatWindow() {
  return window['go']['handler']['WindowHandler']['UnpinFloatWindow']();
}
