package database

// GetDefaultWords 返回默认词库
func GetDefaultWords() []Word {
	return []Word{
		{Word: "abandon", Phonetic: "/əˈbændən/", Translation: "放弃；遗弃", PartOfSpeech: "v.", ExampleSentence: "They had to abandon the plan.", Difficulty: 2},
		{Word: "ability", Phonetic: "/əˈbɪləti/", Translation: "能力；才能", PartOfSpeech: "n.", ExampleSentence: "She has the ability to solve complex problems.", Difficulty: 1},
		{Word: "abroad", Phonetic: "/əˈbrɔːd/", Translation: "在国外；到国外", PartOfSpeech: "adv.", ExampleSentence: "He wants to study abroad next year.", Difficulty: 1},
		{Word: "absent", Phonetic: "/ˈæbsənt/", Translation: "缺席的；不在的", PartOfSpeech: "adj.", ExampleSentence: "He was absent from school yesterday.", Difficulty: 2},
		{Word: "absorb", Phonetic: "/əbˈzɔːb/", Translation: "吸收；吸引", PartOfSpeech: "v.", ExampleSentence: "The fabric absorbs water quickly.", Difficulty: 2},
		{Word: "abstract", Phonetic: "/ˈæbstrækt/", Translation: "抽象的；摘要", PartOfSpeech: "adj./n.", ExampleSentence: "The concept is too abstract to understand.", Difficulty: 3},
		{Word: "accent", Phonetic: "/ˈæksent/", Translation: "口音；重音", PartOfSpeech: "n.", ExampleSentence: "She speaks English with a French accent.", Difficulty: 1},
		{Word: "accept", Phonetic: "/əkˈsept/", Translation: "接受；承认", PartOfSpeech: "v.", ExampleSentence: "I accept your apology.", Difficulty: 1},
		{Word: "access", Phonetic: "/ˈækses/", Translation: "通道；进入；访问", PartOfSpeech: "n./v.", ExampleSentence: "You need a password to access the system.", Difficulty: 1},
		{Word: "achieve", Phonetic: "/əˈtʃiːv/", Translation: "实现；达到；取得", PartOfSpeech: "v.", ExampleSentence: "She worked hard to achieve her goal.", Difficulty: 1},
		{Word: "acquire", Phonetic: "/əˈkwaɪər/", Translation: "获得；学到", PartOfSpeech: "v.", ExampleSentence: "It took years to acquire this skill.", Difficulty: 2},
		{Word: "adapt", Phonetic: "/əˈdæpt/", Translation: "适应；改编", PartOfSpeech: "v.", ExampleSentence: "Animals must adapt to their environment.", Difficulty: 2},
		{Word: "adequate", Phonetic: "/ˈædɪkwət/", Translation: "足够的；充分的", PartOfSpeech: "adj.", ExampleSentence: "The supply is adequate for our needs.", Difficulty: 3},
		{Word: "adjust", Phonetic: "/əˈdʒʌst/", Translation: "调整；适应", PartOfSpeech: "v.", ExampleSentence: "You need to adjust the settings.", Difficulty: 2},
		{Word: "admire", Phonetic: "/ədˈmaɪər/", Translation: "钦佩；赞赏", PartOfSpeech: "v.", ExampleSentence: "I admire your courage.", Difficulty: 2},
		{Word: "adopt", Phonetic: "/əˈdɒpt/", Translation: "采纳；收养", PartOfSpeech: "v.", ExampleSentence: "They decided to adopt a child.", Difficulty: 2},
		{Word: "advance", Phonetic: "/ədˈvɑːns/", Translation: "前进；进步；预付", PartOfSpeech: "v./n.", ExampleSentence: "Technology continues to advance rapidly.", Difficulty: 2},
		{Word: "advantage", Phonetic: "/ədˈvɑːntɪdʒ/", Translation: "优势；有利条件", PartOfSpeech: "n.", ExampleSentence: "Being tall is an advantage in basketball.", Difficulty: 1},
		{Word: "adventure", Phonetic: "/ədˈventʃər/", Translation: "冒险；奇遇", PartOfSpeech: "n.", ExampleSentence: "They set out on an exciting adventure.", Difficulty: 1},
		{Word: "affect", Phonetic: "/əˈfekt/", Translation: "影响；感动", PartOfSpeech: "v.", ExampleSentence: "The weather affects my mood.", Difficulty: 1},
		{Word: "afford", Phonetic: "/əˈfɔːd/", Translation: "负担得起；提供", PartOfSpeech: "v.", ExampleSentence: "I can't afford a new car right now.", Difficulty: 1},
		{Word: "aggressive", Phonetic: "/əˈɡresɪv/", Translation: "侵略的；好斗的；积极的", PartOfSpeech: "adj.", ExampleSentence: "He has an aggressive marketing strategy.", Difficulty: 3},
		{Word: "allocate", Phonetic: "/ˈæləkeɪt/", Translation: "分配；拨出", PartOfSpeech: "v.", ExampleSentence: "The funds were allocated to education.", Difficulty: 3},
		{Word: "alternative", Phonetic: "/ɔːlˈtɜːnətɪv/", Translation: "替代的；可供选择的", PartOfSpeech: "adj./n.", ExampleSentence: "We need to find an alternative solution.", Difficulty: 2},
		{Word: "amaze", Phonetic: "/əˈmeɪz/", Translation: "使惊奇；使惊愕", PartOfSpeech: "v.", ExampleSentence: "Her performance amazed the audience.", Difficulty: 2},
		{Word: "ambition", Phonetic: "/æmˈbɪʃən/", Translation: "抱负；野心", PartOfSpeech: "n.", ExampleSentence: "He has great ambition to become a leader.", Difficulty: 2},
		{Word: "analyze", Phonetic: "/ˈænəlaɪz/", Translation: "分析；解析", PartOfSpeech: "v.", ExampleSentence: "We need to analyze the data carefully.", Difficulty: 2},
		{Word: "announce", Phonetic: "/əˈnaʊns/", Translation: "宣布；通告", PartOfSpeech: "v.", ExampleSentence: "They will announce the winner tomorrow.", Difficulty: 1},
		{Word: "anxiety", Phonetic: "/æŋˈzaɪəti/", Translation: "焦虑；忧虑", PartOfSpeech: "n.", ExampleSentence: "She felt anxiety before the exam.", Difficulty: 2},
		{Word: "apparent", Phonetic: "/əˈpærənt/", Translation: "明显的；表面上的", PartOfSpeech: "adj.", ExampleSentence: "It was apparent that he was lying.", Difficulty: 3},
		{Word: "appeal", Phonetic: "/əˈpiːl/", Translation: "呼吁；吸引；上诉", PartOfSpeech: "v./n.", ExampleSentence: "The idea appeals to many people.", Difficulty: 2},
		{Word: "appetite", Phonetic: "/ˈæpɪtaɪt/", Translation: "食欲；胃口；欲望", PartOfSpeech: "n.", ExampleSentence: "I have a good appetite today.", Difficulty: 2},
		{Word: "appreciate", Phonetic: "/əˈpriːʃieɪt/", Translation: "欣赏；感激；领会", PartOfSpeech: "v.", ExampleSentence: "I really appreciate your help.", Difficulty: 2},
		{Word: "approach", Phonetic: "/əˈprəʊtʃ/", Translation: "接近；方法；途径", PartOfSpeech: "v./n.", ExampleSentence: "We need a new approach to this problem.", Difficulty: 2},
		{Word: "appropriate", Phonetic: "/əˈprəʊpriət/", Translation: "适当的；恰当的", PartOfSpeech: "adj.", ExampleSentence: "Please wear appropriate clothing for the occasion.", Difficulty: 3},
		{Word: "approve", Phonetic: "/əˈpruːv/", Translation: "批准；赞成", PartOfSpeech: "v.", ExampleSentence: "The committee approved the proposal.", Difficulty: 2},
		{Word: "arrange", Phonetic: "/əˈreɪndʒ/", Translation: "安排；整理", PartOfSpeech: "v.", ExampleSentence: "I'll arrange a meeting for next week.", Difficulty: 2},
		{Word: "assess", Phonetic: "/əˈses/", Translation: "评估；评定", PartOfSpeech: "v.", ExampleSentence: "We need to assess the damage first.", Difficulty: 3},
		{Word: "assign", Phonetic: "/əˈsaɪn/", Translation: "分配；指派；布置", PartOfSpeech: "v.", ExampleSentence: "The teacher assigned homework for the weekend.", Difficulty: 2},
		{Word: "assist", Phonetic: "/əˈsɪst/", Translation: "帮助；协助", PartOfSpeech: "v.", ExampleSentence: "Can you assist me with this task?", Difficulty: 1},
		{Word: "assume", Phonetic: "/əˈsjuːm/", Translation: "假设；承担；呈现", PartOfSpeech: "v.", ExampleSentence: "I assume you have read the report.", Difficulty: 2},
		{Word: "atmosphere", Phonetic: "/ˈætməsfɪər/", Translation: "大气；气氛；环境", PartOfSpeech: "n.", ExampleSentence: "The restaurant has a cozy atmosphere.", Difficulty: 2},
		{Word: "attach", Phonetic: "/əˈtætʃ/", Translation: "附上；贴上；依恋", PartOfSpeech: "v.", ExampleSentence: "Please attach the file to the email.", Difficulty: 2},
		{Word: "attempt", Phonetic: "/əˈtempt/", Translation: "尝试；企图", PartOfSpeech: "v./n.", ExampleSentence: "He attempted to climb the mountain.", Difficulty: 1},
		{Word: "attitude", Phonetic: "/ˈætɪtjuːd/", Translation: "态度；看法", PartOfSpeech: "n.", ExampleSentence: "She has a positive attitude towards life.", Difficulty: 1},
		{Word: "attract", Phonetic: "/əˈtrækt/", Translation: "吸引；引起", PartOfSpeech: "v.", ExampleSentence: "The exhibition attracted many visitors.", Difficulty: 1},
		{Word: "authority", Phonetic: "/ɔːˈθɒrəti/", Translation: "权威；当局；权力", PartOfSpeech: "n.", ExampleSentence: "The local authority is responsible for education.", Difficulty: 3},
		{Word: "available", Phonetic: "/əˈveɪləbl/", Translation: "可用的；有效的；有空的", PartOfSpeech: "adj.", ExampleSentence: "Are you available for a meeting tomorrow?", Difficulty: 1},
		{Word: "average", Phonetic: "/ˈævərɪdʒ/", Translation: "平均的；普通的；平均数", PartOfSpeech: "adj./n.", ExampleSentence: "His grades are above average.", Difficulty: 1},
		{Word: "avoid", Phonetic: "/əˈvɔɪd/", Translation: "避免；回避", PartOfSpeech: "v.", ExampleSentence: "You should avoid eating too much sugar.", Difficulty: 1},
		{Word: "aware", Phonetic: "/əˈweər/", Translation: "意识到的；知道的", PartOfSpeech: "adj.", ExampleSentence: "Are you aware of the risks involved?", Difficulty: 2},
		{Word: "balance", Phonetic: "/ˈbæləns/", Translation: "平衡；余额；称", PartOfSpeech: "n./v.", ExampleSentence: "You need to balance work and life.", Difficulty: 1},
		{Word: "barrier", Phonetic: "/ˈbæriər/", Translation: "障碍；屏障", PartOfSpeech: "n.", ExampleSentence: "Language can be a barrier to communication.", Difficulty: 2},
		{Word: "behave", Phonetic: "/bɪˈheɪv/", Translation: "行为；表现；举止", PartOfSpeech: "v.", ExampleSentence: "Children should behave well in public.", Difficulty: 2},
		{Word: "belief", Phonetic: "/bɪˈliːf/", Translation: "信念；相信；信仰", PartOfSpeech: "n.", ExampleSentence: "It is my belief that hard work pays off.", Difficulty: 2},
		{Word: "benefit", Phonetic: "/ˈbenɪfɪt/", Translation: "好处；利益；受益", PartOfSpeech: "n./v.", ExampleSentence: "Regular exercise has many benefits.", Difficulty: 1},
		{Word: "bother", Phonetic: "/ˈbɒðər/", Translation: "打扰；烦恼；麻烦", PartOfSpeech: "v./n.", ExampleSentence: "Don't bother him while he's working.", Difficulty: 2},
		{Word: "boundary", Phonetic: "/ˈbaʊndri/", Translation: "边界；界限", PartOfSpeech: "n.", ExampleSentence: "The river forms the boundary between the two countries.", Difficulty: 3},
		{Word: "capable", Phonetic: "/ˈkeɪpəbl/", Translation: "有能力的；能干的", PartOfSpeech: "adj.", ExampleSentence: "She is a capable leader.", Difficulty: 2},
		{Word: "capture", Phonetic: "/ˈkæptʃər/", Translation: "捕获；夺取；吸引", PartOfSpeech: "v.", ExampleSentence: "The photographer captured the perfect moment.", Difficulty: 2},
		{Word: "challenge", Phonetic: "/ˈtʃælɪndʒ/", Translation: "挑战；质疑", PartOfSpeech: "n./v.", ExampleSentence: "Learning a new language is a challenge.", Difficulty: 1},
		{Word: "character", Phonetic: "/ˈkærəktər/", Translation: "性格；角色；字符", PartOfSpeech: "n.", ExampleSentence: "He is a man of strong character.", Difficulty: 1},
		{Word: "collapse", Phonetic: "/kəˈlæps/", Translation: "倒塌；崩溃；瓦解", PartOfSpeech: "v./n.", ExampleSentence: "The building collapsed in the earthquake.", Difficulty: 3},
		{Word: "command", Phonetic: "/kəˈmɑːnd/", Translation: "命令；指挥；掌握", PartOfSpeech: "v./n.", ExampleSentence: "He commands great respect from his colleagues.", Difficulty: 2},
		{Word: "communicate", Phonetic: "/kəˈmjuːnɪkeɪt/", Translation: "交流；沟通；传达", PartOfSpeech: "v.", ExampleSentence: "We need to communicate more effectively.", Difficulty: 1},
		{Word: "companion", Phonetic: "/kəmˈpænjən/", Translation: "同伴；伙伴", PartOfSpeech: "n.", ExampleSentence: "Dogs are loyal companions.", Difficulty: 2},
		{Word: "compete", Phonetic: "/kəmˈpiːt/", Translation: "竞争；比赛", PartOfSpeech: "v.", ExampleSentence: "Athletes from all over the world compete in the Olympics.", Difficulty: 2},
		{Word: "complain", Phonetic: "/kəmˈpleɪn/", Translation: "抱怨；投诉", PartOfSpeech: "v.", ExampleSentence: "Customers often complain about the service.", Difficulty: 2},
		{Word: "complex", Phonetic: "/ˈkɒmpleks/", Translation: "复杂的；综合体", PartOfSpeech: "adj./n.", ExampleSentence: "The problem is more complex than it seems.", Difficulty: 2},
		{Word: "concentrate", Phonetic: "/ˈkɒnsəntreɪt/", Translation: "集中；专注", PartOfSpeech: "v.", ExampleSentence: "I need to concentrate on my studies.", Difficulty: 2},
		{Word: "conclude", Phonetic: "/kənˈkluːd/", Translation: "总结；得出结论；结束", PartOfSpeech: "v.", ExampleSentence: "What can you conclude from the evidence?", Difficulty: 2},
		{Word: "confident", Phonetic: "/ˈkɒnfɪdənt/", Translation: "自信的；有信心的", PartOfSpeech: "adj.", ExampleSentence: "She is confident about passing the exam.", Difficulty: 1},
		{Word: "conflict", Phonetic: "/ˈkɒnflɪkt/", Translation: "冲突；矛盾；斗争", PartOfSpeech: "n./v.", ExampleSentence: "The conflict between the two countries lasted for years.", Difficulty: 2},
		{Word: "conscious", Phonetic: "/ˈkɒnʃəs/", Translation: "有意识的；自觉的", PartOfSpeech: "adj.", ExampleSentence: "He was conscious of the danger.", Difficulty: 3},
		{Word: "consequence", Phonetic: "/ˈkɒnsɪkwəns/", Translation: "结果；后果", PartOfSpeech: "n.", ExampleSentence: "Every action has a consequence.", Difficulty: 2},
		{Word: "conservation", Phonetic: "/ˌkɒnsəˈveɪʃən/", Translation: "保护；保存；节约", PartOfSpeech: "n.", ExampleSentence: "Wildlife conservation is very important.", Difficulty: 3},
		{Word: "contribute", Phonetic: "/kənˈtrɪbjuːt/", Translation: "贡献；捐献；促成", PartOfSpeech: "v.", ExampleSentence: "Everyone should contribute to the team.", Difficulty: 2},
		{Word: "convince", Phonetic: "/kənˈvɪns/", Translation: "使确信；说服", PartOfSpeech: "v.", ExampleSentence: "I convinced him to change his mind.", Difficulty: 2},
		{Word: "courage", Phonetic: "/ˈkʌrɪdʒ/", Translation: "勇气；胆量", PartOfSpeech: "n.", ExampleSentence: "It takes courage to admit your mistakes.", Difficulty: 1},
		{Word: "creative", Phonetic: "/kriˈeɪtɪv/", Translation: "创造性的；有创意的", PartOfSpeech: "adj.", ExampleSentence: "She has a very creative mind.", Difficulty: 2},
		{Word: "curious", Phonetic: "/ˈkjʊəriəs/", Translation: "好奇的；求知欲强的", PartOfSpeech: "adj.", ExampleSentence: "Children are naturally curious about everything.", Difficulty: 1},
		{Word: "decade", Phonetic: "/ˈdekeɪd/", Translation: "十年；十年期", PartOfSpeech: "n.", ExampleSentence: "Technology has changed a lot in the past decade.", Difficulty: 2},
		{Word: "decline", Phonetic: "/dɪˈklaɪn/", Translation: "下降；衰退；拒绝", PartOfSpeech: "v./n.", ExampleSentence: "The population of the village has declined.", Difficulty: 2},
		{Word: "defeat", Phonetic: "/dɪˈfiːt/", Translation: "击败；战胜；失败", PartOfSpeech: "v./n.", ExampleSentence: "They defeated the opposing team easily.", Difficulty: 2},
		{Word: "deliver", Phonetic: "/dɪˈlɪvər/", Translation: "递送；发表；交付", PartOfSpeech: "v.", ExampleSentence: "The package was delivered this morning.", Difficulty: 1},
		{Word: "demand", Phonetic: "/dɪˈmɑːnd/", Translation: "要求；需求；需要", PartOfSpeech: "n./v.", ExampleSentence: "There is a high demand for skilled workers.", Difficulty: 2},
		{Word: "deserve", Phonetic: "/dɪˈzɜːv/", Translation: "应得；值得", PartOfSpeech: "v.", ExampleSentence: "You deserve a break after all that work.", Difficulty: 2},
		{Word: "determine", Phonetic: "/dɪˈtɜːmɪn/", Translation: "决定；确定；测定", PartOfSpeech: "v.", ExampleSentence: "We need to determine the cause of the problem.", Difficulty: 2},
		{Word: "discover", Phonetic: "/dɪˈskʌvər/", Translation: "发现；发觉", PartOfSpeech: "v.", ExampleSentence: "Scientists discovered a new species.", Difficulty: 1},
		{Word: "display", Phonetic: "/dɪˈspleɪ/", Translation: "显示；展示；陈列", PartOfSpeech: "v./n.", ExampleSentence: "The museum displays ancient artifacts.", Difficulty: 2},
		{Word: "distinguish", Phonetic: "/dɪˈstɪŋɡwɪʃ/", Translation: "区分；辨别；使杰出", PartOfSpeech: "v.", ExampleSentence: "Can you distinguish between the two sounds?", Difficulty: 3},
		{Word: "distribute", Phonetic: "/dɪˈstrɪbjuːt/", Translation: "分配；分发；分布", PartOfSpeech: "v.", ExampleSentence: "The teacher distributed the test papers.", Difficulty: 3},
		{Word: "domestic", Phonetic: "/dəˈmestɪk/", Translation: "国内的；家庭的；驯养的", PartOfSpeech: "adj.", ExampleSentence: "The domestic economy is growing steadily.", Difficulty: 3},
		{Word: "efficient", Phonetic: "/ɪˈfɪʃənt/", Translation: "高效的；有效率的", PartOfSpeech: "adj.", ExampleSentence: "This new system is more efficient than the old one.", Difficulty: 2},
		{Word: "eliminate", Phonetic: "/ɪˈlɪmɪneɪt/", Translation: "消除；淘汰；排除", PartOfSpeech: "v.", ExampleSentence: "We need to eliminate all errors.", Difficulty: 3},
		{Word: "emergency", Phonetic: "/ɪˈmɜːdʒənsi/", Translation: "紧急情况；突发事件", PartOfSpeech: "n.", ExampleSentence: "Call 911 in an emergency.", Difficulty: 2},
		{Word: "emotion", Phonetic: "/ɪˈməʊʃən/", Translation: "情感；情绪", PartOfSpeech: "n.", ExampleSentence: "She couldn't control her emotions.", Difficulty: 2},
		{Word: "emphasize", Phonetic: "/ˈemfəsaɪz/", Translation: "强调；着重", PartOfSpeech: "v.", ExampleSentence: "The teacher emphasized the importance of practice.", Difficulty: 3},
		{Word: "encounter", Phonetic: "/ɪnˈkaʊntər/", Translation: "遭遇；邂逅；遇到", PartOfSpeech: "v./n.", ExampleSentence: "I encountered an old friend on the street.", Difficulty: 3},
		{Word: "enormous", Phonetic: "/ɪˈnɔːməs/", Translation: "巨大的；庞大的", PartOfSpeech: "adj.", ExampleSentence: "The project requires an enormous amount of money.", Difficulty: 3},
		{Word: "establish", Phonetic: "/ɪˈstæblɪʃ/", Translation: "建立；确立；安置", PartOfSpeech: "v.", ExampleSentence: "The company was established in 1990.", Difficulty: 2},
		{Word: "evaluate", Phonetic: "/ɪˈvæljueɪt/", Translation: "评估；评价；估值", PartOfSpeech: "v.", ExampleSentence: "We need to evaluate the results carefully.", Difficulty: 3},
		{Word: "evidence", Phonetic: "/ˈevɪdəns/", Translation: "证据；迹象；证明", PartOfSpeech: "n.", ExampleSentence: "There is no evidence to support his claim.", Difficulty: 2},
		{Word: "evolve", Phonetic: "/ɪˈvɒlv/", Translation: "进化；发展；演变", PartOfSpeech: "v.", ExampleSentence: "Species evolve over millions of years.", Difficulty: 3},
		{Word: "examine", Phonetic: "/ɪɡˈzæmɪn/", Translation: "检查；考试；审视", PartOfSpeech: "v.", ExampleSentence: "The doctor examined the patient thoroughly.", Difficulty: 2},
		{Word: "expand", Phonetic: "/ɪkˈspænd/", Translation: "扩大；扩展；膨胀", PartOfSpeech: "v.", ExampleSentence: "The company plans to expand its business.", Difficulty: 2},
		{Word: "expect", Phonetic: "/ɪkˈspekt/", Translation: "期望；预期；期待", PartOfSpeech: "v.", ExampleSentence: "I expect good results from you.", Difficulty: 1},
		{Word: "experiment", Phonetic: "/ɪkˈsperɪmənt/", Translation: "实验；试验", PartOfSpeech: "n./v.", ExampleSentence: "The experiment proved the theory.", Difficulty: 2},
		{Word: "expert", Phonetic: "/ˈekspɜːt/", Translation: "专家；行家；熟练的", PartOfSpeech: "n./adj.", ExampleSentence: "She is an expert in computer science.", Difficulty: 1},
		{Word: "explore", Phonetic: "/ɪkˈsplɔːr/", Translation: "探索；探险；考察", PartOfSpeech: "v.", ExampleSentence: "We want to explore the possibility of cooperation.", Difficulty: 2},
	}
}
