package method

import "Lancio/database/entity"

// GetDefaultWords 返回默认词库
func GetDefaultWords() []entity.Vocabulary {
	return []entity.Vocabulary{
		{Word: "abandon", Phonetic: "/əˈbændən/", Translation: "v. 放弃；遗弃", ExampleSentence: "They had to abandon the plan."},
		{Word: "ability", Phonetic: "/əˈbɪləti/", Translation: "n. 能力；才能", ExampleSentence: "She has the ability to solve complex problems."},
		{Word: "abroad", Phonetic: "/əˈbrɔːd/", Translation: "adv. 在国外；到国外", ExampleSentence: "He wants to study abroad next year."},
		{Word: "absent", Phonetic: "/ˈæbsənt/", Translation: "adj. 缺席的；不在的", ExampleSentence: "He was absent from school yesterday."},
		{Word: "absorb", Phonetic: "/əbˈzɔːb/", Translation: "v. 吸收；吸引", ExampleSentence: "The fabric absorbs water quickly."},
		{Word: "abstract", Phonetic: "/ˈæbstrækt/", Translation: "adj. 抽象的 n. 摘要", ExampleSentence: "The concept is too abstract to understand."},
		{Word: "accent", Phonetic: "/ˈæksent/", Translation: "n. 口音；重音", ExampleSentence: "She speaks English with a French accent."},
		{Word: "accept", Phonetic: "/əkˈsept/", Translation: "v. 接受；承认", ExampleSentence: "I accept your apology."},
		{Word: "access", Phonetic: "/ˈækses/", Translation: "n. 通道；进入 v. 访问", ExampleSentence: "You need a password to access the system."},
		{Word: "achieve", Phonetic: "/əˈtʃiːv/", Translation: "v. 实现；达到；取得", ExampleSentence: "She worked hard to achieve her goal."},
		{Word: "acquire", Phonetic: "/əˈkwaɪər/", Translation: "v. 获得；学到", ExampleSentence: "It took years to acquire this skill."},
		{Word: "adapt", Phonetic: "/əˈdæpt/", Translation: "v. 适应；改编", ExampleSentence: "Animals must adapt to their environment."},
		{Word: "adequate", Phonetic: "/ˈædɪkwət/", Translation: "adj. 足够的；充分的", ExampleSentence: "The supply is adequate for our needs."},
		{Word: "adjust", Phonetic: "/əˈdʒʌst/", Translation: "v. 调整；适应", ExampleSentence: "You need to adjust the settings."},
		{Word: "admire", Phonetic: "/ədˈmaɪər/", Translation: "v. 钦佩；赞赏", ExampleSentence: "I admire your courage."},
		{Word: "adopt", Phonetic: "/əˈdɒpt/", Translation: "v. 采纳；收养", ExampleSentence: "They decided to adopt a child."},
		{Word: "advance", Phonetic: "/ədˈvɑːns/", Translation: "v. 前进；进步 n. 预付", ExampleSentence: "Technology continues to advance rapidly."},
		{Word: "advantage", Phonetic: "/ədˈvɑːntɪdʒ/", Translation: "n. 优势；有利条件", ExampleSentence: "Being tall is an advantage in basketball."},
		{Word: "adventure", Phonetic: "/ədˈventʃər/", Translation: "n. 冒险；奇遇", ExampleSentence: "They set out on an exciting adventure."},
		{Word: "affect", Phonetic: "/əˈfekt/", Translation: "v. 影响；感动", ExampleSentence: "The weather affects my mood."},
		{Word: "afford", Phonetic: "/əˈfɔːd/", Translation: "v. 负担得起；提供", ExampleSentence: "I can't afford a new car right now."},
		{Word: "aggressive", Phonetic: "/əˈɡresɪv/", Translation: "adj. 侵略的；好斗的；积极的", ExampleSentence: "He has an aggressive marketing strategy."},
		{Word: "allocate", Phonetic: "/ˈæləkeɪt/", Translation: "v. 分配；拨出", ExampleSentence: "The funds were allocated to education."},
		{Word: "alternative", Phonetic: "/ɔːlˈtɜːnətɪv/", Translation: "adj. 替代的 n. 可供选择", ExampleSentence: "We need to find an alternative solution."},
		{Word: "amaze", Phonetic: "/əˈmeɪz/", Translation: "v. 使惊奇；使惊愕", ExampleSentence: "Her performance amazed the audience."},
		{Word: "ambition", Phonetic: "/æmˈbɪʃən/", Translation: "n. 抱负；野心", ExampleSentence: "He has great ambition to become a leader."},
		{Word: "analyze", Phonetic: "/ˈænəlaɪz/", Translation: "v. 分析；解析", ExampleSentence: "We need to analyze the data carefully."},
		{Word: "announce", Phonetic: "/əˈnaʊns/", Translation: "v. 宣布；通告", ExampleSentence: "They will announce the winner tomorrow."},
		{Word: "anxiety", Phonetic: "/æŋˈzaɪəti/", Translation: "n. 焦虑；忧虑", ExampleSentence: "She felt anxiety before the exam."},
		{Word: "apparent", Phonetic: "/əˈpærənt/", Translation: "adj. 明显的；表面上的", ExampleSentence: "It was apparent that he was lying."},
		{Word: "appeal", Phonetic: "/əˈpiːl/", Translation: "v. 呼吁；吸引 n. 上诉", ExampleSentence: "The idea appeals to many people."},
		{Word: "appetite", Phonetic: "/ˈæpɪtaɪt/", Translation: "n. 食欲；胃口；欲望", ExampleSentence: "I have a good appetite today."},
		{Word: "appreciate", Phonetic: "/əˈpriːʃieɪt/", Translation: "v. 欣赏；感激；领会", ExampleSentence: "I really appreciate your help."},
		{Word: "approach", Phonetic: "/əˈprəʊtʃ/", Translation: "v. 接近 n. 方法；途径", ExampleSentence: "We need a new approach to this problem."},
		{Word: "appropriate", Phonetic: "/əˈprəʊpriət/", Translation: "adj. 适当的；恰当的", ExampleSentence: "Please wear appropriate clothing for the occasion."},
		{Word: "approve", Phonetic: "/əˈpruːv/", Translation: "v. 批准；赞成", ExampleSentence: "The committee approved the proposal."},
		{Word: "arrange", Phonetic: "/əˈreɪndʒ/", Translation: "v. 安排；整理", ExampleSentence: "I'll arrange a meeting for next week."},
		{Word: "assess", Phonetic: "/əˈses/", Translation: "v. 评估；评定", ExampleSentence: "We need to assess the damage first."},
		{Word: "assign", Phonetic: "/əˈsaɪn/", Translation: "v. 分配；指派；布置", ExampleSentence: "The teacher assigned homework for the weekend."},
		{Word: "assist", Phonetic: "/əˈsɪst/", Translation: "v. 帮助；协助", ExampleSentence: "Can you assist me with this task?"},
		{Word: "assume", Phonetic: "/əˈsjuːm/", Translation: "v. 假设；承担；呈现", ExampleSentence: "I assume you have read the report."},
		{Word: "atmosphere", Phonetic: "/ˈætməsfɪər/", Translation: "n. 大气；气氛；环境", ExampleSentence: "The restaurant has a cozy atmosphere."},
		{Word: "attach", Phonetic: "/əˈtætʃ/", Translation: "v. 附上；贴上；依恋", ExampleSentence: "Please attach the file to the email."},
		{Word: "attempt", Phonetic: "/əˈtempt/", Translation: "v. 尝试 n. 企图", ExampleSentence: "He attempted to climb the mountain."},
		{Word: "attitude", Phonetic: "/ˈætɪtjuːd/", Translation: "n. 态度；看法", ExampleSentence: "She has a positive attitude towards life."},
		{Word: "attract", Phonetic: "/əˈtrækt/", Translation: "v. 吸引；引起", ExampleSentence: "The exhibition attracted many visitors."},
		{Word: "authority", Phonetic: "/ɔːˈθɒrəti/", Translation: "n. 权威；当局；权力", ExampleSentence: "The local authority is responsible for education."},
		{Word: "available", Phonetic: "/əˈveɪləbl/", Translation: "adj. 可用的；有效的；有空的", ExampleSentence: "Are you available for a meeting tomorrow?"},
		{Word: "average", Phonetic: "/ˈævərɪdʒ/", Translation: "adj. 平均的；普通的 n. 平均数", ExampleSentence: "His grades are above average."},
		{Word: "avoid", Phonetic: "/əˈvɔɪd/", Translation: "v. 避免；回避", ExampleSentence: "You should avoid eating too much sugar."},
		{Word: "aware", Phonetic: "/əˈweər/", Translation: "adj. 意识到的；知道的", ExampleSentence: "Are you aware of the risks involved?"},
		{Word: "balance", Phonetic: "/ˈbæləns/", Translation: "n. 平衡；余额 v. 称", ExampleSentence: "You need to balance work and life."},
		{Word: "barrier", Phonetic: "/ˈbæriər/", Translation: "n. 障碍；屏障", ExampleSentence: "Language can be a barrier to communication."},
		{Word: "behave", Phonetic: "/bɪˈheɪv/", Translation: "v. 行为；表现；举止", ExampleSentence: "Children should behave well in public."},
		{Word: "belief", Phonetic: "/bɪˈliːf/", Translation: "n. 信念；相信；信仰", ExampleSentence: "It is my belief that hard work pays off."},
		{Word: "benefit", Phonetic: "/ˈbenɪfɪt/", Translation: "n. 好处；利益 v. 受益", ExampleSentence: "Regular exercise has many benefits."},
		{Word: "bother", Phonetic: "/ˈbɒðər/", Translation: "v. 打扰 n. 烦恼；麻烦", ExampleSentence: "Don't bother him while he's working."},
		{Word: "boundary", Phonetic: "/ˈbaʊndri/", Translation: "n. 边界；界限", ExampleSentence: "The river forms the boundary between the two countries."},
		{Word: "capable", Phonetic: "/ˈkeɪpəbl/", Translation: "adj. 有能力的；能干的", ExampleSentence: "She is a capable leader."},
		{Word: "capture", Phonetic: "/ˈkæptʃər/", Translation: "v. 捕获；夺取；吸引", ExampleSentence: "The photographer captured the perfect moment."},
		{Word: "challenge", Phonetic: "/ˈtʃælɪndʒ/", Translation: "n. 挑战 v. 质疑", ExampleSentence: "Learning a new language is a challenge."},
		{Word: "character", Phonetic: "/ˈkærəktər/", Translation: "n. 性格；角色；字符", ExampleSentence: "He is a man of strong character."},
		{Word: "collapse", Phonetic: "/kəˈlæps/", Translation: "v. 倒塌；崩溃 n. 瓦解", ExampleSentence: "The building collapsed in the earthquake."},
		{Word: "command", Phonetic: "/kəˈmɑːnd/", Translation: "v. 命令；指挥 n. 掌握", ExampleSentence: "He commands great respect from his colleagues."},
		{Word: "communicate", Phonetic: "/kəˈmjuːnɪkeɪt/", Translation: "v. 交流；沟通；传达", ExampleSentence: "We need to communicate more effectively."},
		{Word: "companion", Phonetic: "/kəmˈpænjən/", Translation: "n. 同伴；伙伴", ExampleSentence: "Dogs are loyal companions."},
		{Word: "compete", Phonetic: "/kəmˈpiːt/", Translation: "v. 竞争；比赛", ExampleSentence: "Athletes from all over the world compete in the Olympics."},
		{Word: "complain", Phonetic: "/kəmˈpleɪn/", Translation: "v. 抱怨；投诉", ExampleSentence: "Customers often complain about the service."},
		{Word: "complex", Phonetic: "/ˈkɒmpleks/", Translation: "adj. 复杂的 n. 综合体", ExampleSentence: "The problem is more complex than it seems."},
		{Word: "concentrate", Phonetic: "/ˈkɒnsəntreɪt/", Translation: "v. 集中；专注", ExampleSentence: "I need to concentrate on my studies."},
		{Word: "conclude", Phonetic: "/kənˈkluːd/", Translation: "v. 总结；得出结论；结束", ExampleSentence: "What can you conclude from the evidence?"},
		{Word: "confident", Phonetic: "/ˈkɒnfɪdənt/", Translation: "adj. 自信的；有信心的", ExampleSentence: "She is confident about passing the exam."},
		{Word: "conflict", Phonetic: "/ˈkɒnflɪkt/", Translation: "n. 冲突；矛盾 v. 斗争", ExampleSentence: "The conflict between the two countries lasted for years."},
		{Word: "conscious", Phonetic: "/ˈkɒnʃəs/", Translation: "adj. 有意识的；自觉的", ExampleSentence: "He was conscious of the danger."},
		{Word: "consequence", Phonetic: "/ˈkɒnsɪkwəns/", Translation: "n. 结果；后果", ExampleSentence: "Every action has a consequence."},
		{Word: "conservation", Phonetic: "/ˌkɒnsəˈveɪʃən/", Translation: "n. 保护；保存；节约", ExampleSentence: "Wildlife conservation is very important."},
		{Word: "contribute", Phonetic: "/kənˈtrɪbjuːt/", Translation: "v. 贡献；捐献；促成", ExampleSentence: "Everyone should contribute to the team."},
		{Word: "convince", Phonetic: "/kənˈvɪns/", Translation: "v. 使确信；说服", ExampleSentence: "I convinced him to change his mind."},
		{Word: "courage", Phonetic: "/ˈkʌrɪdʒ/", Translation: "n. 勇气；胆量", ExampleSentence: "It takes courage to admit your mistakes."},
		{Word: "creative", Phonetic: "/kriˈeɪtɪv/", Translation: "adj. 创造性的；有创意的", ExampleSentence: "She has a very creative mind."},
		{Word: "curious", Phonetic: "/ˈkjʊəriəs/", Translation: "adj. 好奇的；求知欲强的", ExampleSentence: "Children are naturally curious about everything."},
		{Word: "decade", Phonetic: "/ˈdekeɪd/", Translation: "n. 十年；十年期", ExampleSentence: "Technology has changed a lot in the past decade."},
		{Word: "decline", Phonetic: "/dɪˈklaɪn/", Translation: "v. 下降；衰退 n. 拒绝", ExampleSentence: "The population of the village has declined."},
		{Word: "defeat", Phonetic: "/dɪˈfiːt/", Translation: "v. 击败；战胜 n. 失败", ExampleSentence: "They defeated the opposing team easily."},
		{Word: "deliver", Phonetic: "/dɪˈlɪvər/", Translation: "v. 递送；发表；交付", ExampleSentence: "The package was delivered this morning."},
		{Word: "demand", Phonetic: "/dɪˈmɑːnd/", Translation: "n. 要求；需求 v. 需要", ExampleSentence: "There is a high demand for skilled workers."},
		{Word: "deserve", Phonetic: "/dɪˈzɜːv/", Translation: "v. 应得；值得", ExampleSentence: "You deserve a break after all that work."},
		{Word: "determine", Phonetic: "/dɪˈtɜːmɪn/", Translation: "v. 决定；确定；测定", ExampleSentence: "We need to determine the cause of the problem."},
		{Word: "discover", Phonetic: "/dɪˈskʌvər/", Translation: "v. 发现；发觉", ExampleSentence: "Scientists discovered a new species."},
		{Word: "display", Phonetic: "/dɪˈspleɪ/", Translation: "v. 显示；展示 n. 陈列", ExampleSentence: "The museum displays ancient artifacts."},
		{Word: "distinguish", Phonetic: "/dɪˈstɪŋɡwɪʃ/", Translation: "v. 区分；辨别；使杰出", ExampleSentence: "Can you distinguish between the two sounds?"},
		{Word: "distribute", Phonetic: "/dɪˈstrɪbjuːt/", Translation: "v. 分配；分发；分布", ExampleSentence: "The teacher distributed the test papers."},
		{Word: "domestic", Phonetic: "/dəˈmestɪk/", Translation: "adj. 国内的；家庭的；驯养的", ExampleSentence: "The domestic economy is growing steadily."},
		{Word: "efficient", Phonetic: "/ɪˈfɪʃənt/", Translation: "adj. 高效的；有效率的", ExampleSentence: "This new system is more efficient than the old one."},
		{Word: "eliminate", Phonetic: "/ɪˈlɪmɪneɪt/", Translation: "v. 消除；淘汰；排除", ExampleSentence: "We need to eliminate all errors."},
		{Word: "emergency", Phonetic: "/ɪˈmɜːdʒənsi/", Translation: "n. 紧急情况；突发事件", ExampleSentence: "Call 911 in an emergency."},
		{Word: "emotion", Phonetic: "/ɪˈməʊʃən/", Translation: "n. 情感；情绪", ExampleSentence: "She couldn't control her emotions."},
		{Word: "emphasize", Phonetic: "/ˈemfəsaɪz/", Translation: "v. 强调；着重", ExampleSentence: "The teacher emphasized the importance of practice."},
		{Word: "encounter", Phonetic: "/ɪnˈkaʊntər/", Translation: "v. 遭遇；邂逅 n. 遇到", ExampleSentence: "I encountered an old friend on the street."},
		{Word: "enormous", Phonetic: "/ɪˈnɔːməs/", Translation: "adj. 巨大的；庞大的", ExampleSentence: "The project requires an enormous amount of money."},
		{Word: "establish", Phonetic: "/ɪˈstæblɪʃ/", Translation: "v. 建立；确立；安置", ExampleSentence: "The company was established in 1990."},
		{Word: "evaluate", Phonetic: "/ɪˈvæljueɪt/", Translation: "v. 评估；评价；估值", ExampleSentence: "We need to evaluate the results carefully."},
		{Word: "evidence", Phonetic: "/ˈevɪdəns/", Translation: "n. 证据；迹象；证明", ExampleSentence: "There is no evidence to support his claim."},
		{Word: "evolve", Phonetic: "/ɪˈvɒlv/", Translation: "v. 进化；发展；演变", ExampleSentence: "Species evolve over millions of years."},
		{Word: "examine", Phonetic: "/ɪɡˈzæmɪn/", Translation: "v. 检查；考试；审视", ExampleSentence: "The doctor examined the patient thoroughly."},
		{Word: "expand", Phonetic: "/ɪkˈspænd/", Translation: "v. 扩大；扩展；膨胀", ExampleSentence: "The company plans to expand its business."},
		{Word: "expect", Phonetic: "/ɪkˈspekt/", Translation: "v. 期望；预期；期待", ExampleSentence: "I expect good results from you."},
		{Word: "experiment", Phonetic: "/ɪkˈsperɪmənt/", Translation: "n. 实验 v. 试验", ExampleSentence: "The experiment proved the theory."},
		{Word: "expert", Phonetic: "/ˈekspɜːt/", Translation: "n. 专家；行家 adj. 熟练的", ExampleSentence: "She is an expert in computer science."},
		{Word: "explore", Phonetic: "/ɪkˈsplɔːr/", Translation: "v. 探索；探险；考察", ExampleSentence: "We want to explore the possibility of cooperation."},
	}
}
