// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRandomWord() {
  return window['go']['main']['App']['GetRandomWord']();
}

export function GetWordByID(arg1) {
  return window['go']['main']['App']['GetWordByID'](arg1);
}

export function GetWordCount() {
  return window['go']['main']['App']['GetWordCount']();
}

export function GetWordsByRange(arg1, arg2) {
  return window['go']['main']['App']['GetWordsByRange'](arg1, arg2);
}

export function LookupWordDetail(arg1) {
  return window['go']['main']['App']['LookupWordDetail'](arg1);
}

export function SetOpacity(arg1) {
  return window['go']['main']['App']['SetOpacity'](arg1);
}
