// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {services} from '../models';

export function GetRandomWord():Promise<database.Word>;

export function GetWordByID(arg1:number):Promise<database.Word>;

export function GetWordCount():Promise<number>;

export function GetWordsByRange(arg1:number,arg2:number):Promise<Array<database.Word>>;

export function LookupWordDetail(arg1:string):Promise<services.WordDetail>;

export function SetOpacity(arg1:number):Promise<void>;
